name: Deploy to Pratham-DEV-Deployment on Prahtam-AWS
on:
  push:
    branches:
      - shiksha-2.0
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME_PRATHAM_AWS }}
          username: ${{ secrets.USERNAME_PRATHAM_AWS }}
          key: ${{ secrets.EC2_SSH_KEY_PRATHAM_AWS }}
          port: ${{ secrets.PORT_PRATHAM_AWS }}
          script: |
            cd ${{ secrets.TARGET_DIR_PRATHAM_AWS }}
            ./deploy.sh
